import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Meetings} from '../src/service/meeting.js';import {Store} from '../src/service/store.js';import {Capabilities} from '../src/shared/capabilities.js';
const tick=()=>new Promise(r=>setTimeout(r,5));async function until(fn){for(let i=0;i<200;i++){if(fn())return;await tick();}throw new Error('timeout');}
function setup(t,runner){const dir=mkdtempSync(join(tmpdir(),'roundtable-lifecycle-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));return new Meetings({store:new Store(join(dir,'meetings')),capabilities:new Capabilities(join(dir,'shared')),runner});}
const turn=()=>({ok:true,text:JSON.stringify({statement:'fixture',replyTo:['M-001'],claims:[{text:'fixture',kind:'proposal',sources:[],method:'fixture',limitations:''}],readyToConclude:true,openQuestions:['user retains final choice']}),toolCalls:[]});
const decision=()=>({ok:true,text:JSON.stringify({recommendation:'fixture',options:[{name:'x',pros:[],cons:[],evidenceIds:['C-001']}],disagreements:['fixture dissent'],unknowns:['user retains final choice']}),toolCalls:[]});
test('early decision may retain questions for the user rather than force agreement',async t=>{const s=setup(t,async(_id,o)=>o.prompt.includes('"recommendation"')?decision():turn());const m=s.create({organizer:null,topic:'fixture',participants:['codex','claude']});s.start(m.id);await until(()=>!s.active);const done=s.view(m.id);assert.equal(done.round,1);assert.equal(done.decision.status,'provider-draft');assert.equal(done.decision.unknowns.length,1);});
test('pause during last speaker defers summary; resume finalizes without an extra round',async t=>{let release;const gate=new Promise(r=>release=r);const s=setup(t,async(id,o)=>{if(id==='claude'&&!o.prompt.includes('"recommendation"'))await gate;return o.prompt.includes('"recommendation"')?decision():turn();});const m=s.create({organizer:null,topic:'fixture',participants:['codex','claude'],maxRounds:1});s.start(m.id);await until(()=>s.get(m.id).activeParticipant==='claude');s.pause(m.id);release();await until(()=>!s.active);assert.equal(s.view(m.id).status,'paused');assert.equal(s.view(m.id).calls.length,2);s.start(m.id);await until(()=>!s.active);assert.equal(s.view(m.id).calls.length,3);assert.equal(s.view(m.id).round,1);});
test('finish cancels current process and records unavailable decision rather than invent output',async t=>{const s=setup(t,async(_id,o)=>new Promise(resolve=>o.signal.addEventListener('abort',()=>resolve({ok:false,error:'cancelled',toolCalls:[]}))));const m=s.create({organizer:null,topic:'fixture',participants:['codex','claude']});s.start(m.id);s.send(m.id,'pending fixture input');s.finish(m.id);await until(()=>!s.active);const done=s.view(m.id);assert.equal(done.status,'completed');assert.equal(done.messages.length,2);assert.equal(done.messages[1].author,'human');assert.equal(done.decision.status,'record-only');assert.equal(done.messages.filter(m=>m.origin==='provider').length,0);});
