import { _electron as electron } from 'playwright';import {resolve,join} from 'node:path';import {mkdirSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const root=resolve('output/verification/real-desktop');mkdirSync(root,{recursive:true});const env={...process.env,ROUNDTABLE_DATA_DIR:resolve('.roundtable')};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:resolve('dist/Roundtable.app/Contents/MacOS/Electron'),env,timeout:20000});
try{const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByText('本地服务已连接',{exact:true}).waitFor();await page.locator('.meeting-link').first().click();await page.locator('.claim-list button').first().click();await page.locator('#evidence-content h3').first().waitFor();
 const bootstrap=await page.evaluate(()=>window.roundtableDesktop.bootstrap());const exported=await page.evaluate(async b=>{const h={Authorization:'Bearer '+b.token},meetings=await(await fetch(b.url+'/api/meetings',{headers:h})).json();return(await fetch(b.url+'/api/meetings/'+meetings[0].id+'/export',{headers:h})).json();},bootstrap);
 assert.equal(exported.meeting.status,'completed');assert.equal(exported.meeting.decision.status,'provider-draft');assert.ok(exported.artifacts.length>=4);assert.ok(!JSON.stringify(exported).includes(bootstrap.token));assert.ok(exported.artifacts.every(a=>Object.keys(a.files).length===4));
 await page.screenshot({path:join(root,'discussion.png'),fullPage:true});await page.getByRole('tab',{name:'决策稿'}).click();await page.locator('.decision-option').first().waitFor();await page.screenshot({path:join(root,'decision.png'),fullPage:true});assert.deepEqual(errors,[]);
 const verification={ok:true,meetingId:exported.meeting.id,participants:exported.meeting.participants,artifactCalls:exported.artifacts.length,errors,providerCallsDuringPreview:0};writeFileSync(join(root,'result.json'),JSON.stringify(verification,null,2));writeFileSync(join(root,'export.json'),JSON.stringify(exported,null,2));console.log(JSON.stringify(verification));
}finally{await app.close();}
